import OFT_ABI from "./OFT_ABI.json";
import OFT_ADAPTER_ABI from "./OFT_ADAPTER_ABI.json";
import OFT_MINTABLE_ADAPTER_ABI from "./OFT_MINTABLE_ADAPTER_ABI.json";
import ENDPOINTV2_ABI from "./ENDPOINTV2_ABI.json";
import FRAX_PROXY_ADMIN_ABI from "./FRAX_PROXY_ADMIN_ABI.json";
import FRAXTAL_HOP_ABI from "./FRAXTAL_HOP.json";
import FRAXTAL_MINT_REDEEM_HOP_ABI from "./FRAXTAL_MINT_REDEEM_HOP.json";
import RECEIVE_ULN302_ABI from "./RECEIVE_ULN302_ABI.json";
import REMOTE_HOP_ABI from "./REMOTE_HOP_ABI.json";
import REMOTE_MINT_REDEEM_HOP_ABI from "./REMOTE_MINT_REDEEM_HOP.json";
import SEND_ULN302_ABI from "./SEND_ULN302_ABI.json";
import HOP_V2_ABI from "./HOP_V2_ABI.json";
import HOP_V201_ABI from "./HOP_V201_ABI.json";
import REMOTE_ADMIN_V2_ABI from "./REMOTE_ADMIN_V2_ABI.json";
export { ERC20ABI } from "./ERC20";

export {
  OFT_ABI,
  OFT_ADAPTER_ABI,
  OFT_MINTABLE_ADAPTER_ABI,
  ENDPOINTV2_ABI,
  FRAX_PROXY_ADMIN_ABI,
  FRAXTAL_HOP_ABI,
  FRAXTAL_MINT_REDEEM_HOP_ABI,
  RECEIVE_ULN302_ABI,
  REMOTE_HOP_ABI,
  REMOTE_MINT_REDEEM_HOP_ABI,
  SEND_ULN302_ABI,
  HOP_V2_ABI,
  HOP_V201_ABI,
  REMOTE_ADMIN_V2_ABI,
};
